version: '3'
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: django_blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: 123456
      LANG: C.UTF-8
      HOST: blog
    port: 
      - '3306:3306'
    command: ['mysqld','--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci'] 


  blog:
    build: .
    volumes:
      - /data/wwwroot/djang_blog:/code/djang_blog/
    container_name: blog
    vulumes:
      - /data/wwwroot/djang_blog/blog.xml:/code/djang_blog/
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py loaddata blog6.json && python manage.py collectstatici && uwsgi -x blog.xml"
    depends_on:
      - mysql


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /data/wwwroot/djang_blog/default.conf:/etc/nginx/conf.d/default.conf
      - /data/wwwroot/djang_blog/blog.xml:/code/djang_blog/
    ports:
      - '80:80'
    command: ['pip3 install '
    depends_on:
      - blog


